---
driver:
  name: docker
  privileged: true
  use_sudo: false

platforms:
  - name: centos-7
    driver_config:
      require_chef_omnibus: "13.1.31"
      image: centos/systemd
      run_command: /usr/sbin/init
      privileged: true
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
        - yum install net-tools -y && curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 13.1.31 && rm install.sh

  - name: centos-7-chef-12
    driver_config:
      require_chef_omnibus: "12.6.0"
      image: centos/systemd
      run_command: /usr/sbin/init
      privileged: true
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
        - yum install net-tools -y && curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 12.6.0 && rm install.sh

  - name: centos-69
    driver_config:
      require_chef_omnibus: "13.1.31"
      image: centos:6.9
      privileged: true
      provision_command:
        - yum install net-tools -y && curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 13.1.31 && rm install.sh

  - name: centos-69-chef-12
    driver_config:
      require_chef_omnibus: "12.7.2"
      image: centos:6.9
      privileged: true
      provision_command:
        - yum install net-tools -y && curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 12.7.2 && rm install.sh

provisioner:
  name: chef_solo

verifier:
  name: inspec

suites:
  - name: php71
    run_list:
      - recipe[php-omnibus::install_requirements]
      - recipe[php-omnibus]
      - recipe[php-omnibus::php_fpm]
    attributes:
        php-fpm:
          user: nobody
          group: nobody
          package_name: php71u-fpm
          service_name: php-fpm
    verifier:
      inspec_tests:
        - tests/centos/yum.rb
        - tests/centos/php-71.rb
  - name: php72
    run_list:
      - recipe[php-omnibus::install_requirements]
      - recipe[php-omnibus]
      - recipe[php-omnibus::php_fpm]
    attributes:
        php:
          package_version: php72u
        php-fpm:
          user: nobody
          group: nobody
          package_name: php72u-fpm
          service_name: php-fpm
    verifier:
      inspec_tests:
        - tests/centos/yum.rb
        - tests/centos/php-72.rb
