---
driver:
  name: docker
  privileged: true
  use_sudo: false

platforms:
  - name: centos-7
    driver_config:
      image: centos/systemd
      deprecations_as_errors: true
      run_command: /usr/sbin/init
      privileged: true
      provision_command:
        - sed -i 's/UsePAM yes/UsePAM no/g' /etc/ssh/sshd_config
        - systemctl enable sshd.service
        - yum install net-tools -y && curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 13 && rm install.sh

  - name: centos-69
    driver_config:
      image: centos:6.9
      deprecations_as_errors: true
      privileged: true
      provision_command:
        - yum install net-tools -y && curl -LO https://omnitruck.chef.io/install.sh && sudo bash ./install.sh -v 13 && rm install.sh

provisioner:
  name: chef_solo
  chef_license: accept-no-persist

verifier:
  name: inspec

suites:
  - name: php72
    excludes:
      - centos-69
    run_list:
      - recipe[php-omnibus::install_requirements]
      - recipe[php-omnibus]
      - recipe[php-omnibus::php_fpm]
    attributes:
        php-omnibus:
          skip_pear: true
        php:
          package_version: php72u
        php-fpm:
          user: nobody
          group: nobody
          package_name: php72u-fpm
          service_name: php-fpm
    verifier:
      inspec_tests:
        - tests/centos/yum.rb
        - tests/centos/php-72.rb
        - tests/centos/pear_not_installed.rb
  - name: php73
    excludes:
      - centos-69
    run_list:
      - recipe[php-omnibus::install_requirements]
      - recipe[php-omnibus]
      - recipe[php-omnibus::php_fpm]
    attributes:
        php:
          package_version: php73
        php-fpm:
          user: nobody
          group: nobody
          package_name: php73-fpm
          service_name: php-fpm
    verifier:
      inspec_tests:
        - tests/centos/yum.rb
        - tests/centos/php-73.rb
