language: ruby
dist: trusty

matrix:
  include:
    - rvm: 2.4
      env: suite=php72-centos-7
    - rvm: 2.4
      env: suite=php73-centos-7

sudo: required
services: docker

group: deprecated-2017Q2

before_script:
  - make install
  - make bundle
  - make style

script: bundle exec kitchen test "$suite"
