language: ruby

matrix:
  include:
    - rvm: 2.4
      env: suite=centos-7
    - rvm: 2.4
      env: suite=centos-7-chef-12
    - rvm: 2.4
      env: suite=centos-69
    - rvm: 2.4
      env: suite=centos-69-chef-12
    - rvm: 2.4
      env: suite=centos-68

sudo: required
services: docker

install: /bin/true

before_script:
  - make install
  - make bundle
  - make style

script: bundle exec kitchen test "$suite"
